import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {parseSTL,normalizeSTL,isGlass,splitMaterials,buildPanels,samplePanel,fitsPanel} from '../src/stl.mjs';
import {validateGrid,overlap,mapPlacement,placementError} from '../src/placements.mjs';
import {compileStudio,publicConfig} from '../scripts/build.mjs';
const [studio,cloud,css]=await Promise.all(['studio-extension.js','cloud-extension.js','extensions.css'].map(f=>readFile(new URL('../src/'+f,import.meta.url),'utf8')));
const rect={zoneId:'hood',col:0,row:0,cols:4,rows:2,rotation:0};
function binary(points){const b=new ArrayBuffer(84+points.length/9*50),v=new DataView(b);new Uint8Array(b).set(new TextEncoder().encode('solid binary header'));v.setUint32(80,points.length/9,true);for(let f=0;f<points.length/9;f++)for(let j=0;j<9;j++)v.setFloat32(84+f*50+12+j*4,points[f*9+j],true);return b;}
function box(){const p=[[-2.21,0,-.98],[2.21,0,-.98],[2.21,1.2,-.98],[-2.21,1.2,-.98],[-2.21,0,.98],[2.21,0,.98],[2.21,1.2,.98],[-2.21,1.2,.98]];return new Float32Array([[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[3,7,6],[3,6,2],[0,4,7],[0,7,3],[1,2,6],[1,6,5]].flatMap(ids=>ids.flatMap(i=>p[i])));}
test('binary STL including a misleading solid header',()=>assert.equal(parseSTL(binary([0,0,0,1,0,0,0,1,0])).length,9));
test('ASCII STL with exponent coordinates',()=>assert.equal(parseSTL(new TextEncoder().encode('solid a\nvertex 0 0 0\nvertex 1e0 0 0\nvertex 0 1 0\nendsolid a').buffer).length,9));
test('truncated and nonfinite STL fail explicitly',()=>{const b=binary([0,0,0,1,0,0,0,1,0]);assert.throws(()=>parseSTL(b.slice(0,-1)));new DataView(b).setFloat32(96,NaN,true);assert.throws(()=>parseSTL(b));});
test('normalization grounds the car and uses stable physical axes',()=>{const m=normalizeSTL(box());assert.deepEqual(m.axes,[0,1,2]);assert.ok(Math.abs(m.size[0]-4.42)<1e-6);assert.ok(Math.abs(Math.min(...Array.from(m.positions).filter((_,i)=>i%3===1)))<1e-6);assert.throws(()=>normalizeSTL(box(),{axes:[0,0,2]}));});
test('yaw calibration preserves lengths and normals',()=>{const input=box(),a=.23;for(let i=0;i<input.length;i+=3){const x=input[i],z=input[i+2];input[i]=Math.cos(a)*x-Math.sin(a)*z;input[i+2]=Math.sin(a)*x+Math.cos(a)*z;}const m=normalizeSTL(input,{axes:[0,1,2],yawDegrees:a*180/Math.PI});assert.ok(Math.abs(m.size[2]-1.96)<1e-5);for(let i=0;i<m.normals.length;i+=3)assert.ok(Math.abs(Math.hypot(...m.normals.slice(i,i+3))-1)<1e-5);});
test('both side windows are grey; roof and lower body remain white',()=>{const size=[4.42,1.2,1.96];assert.equal(isGlass([0,.96,.7],[0,0,1],size),true);assert.equal(isGlass([0,.96,-.7],[0,0,-1],size),true);assert.equal(isGlass([0,1.2,0],[0,1,0],size),false);assert.equal(isGlass([0,.4,.98],[0,0,1],size),false);});
test('logo surface is projected onto actual STL triangles; holes are rejected',()=>{const m=normalizeSTL(box()),{labels}=splitMaterials(m,{sideWindow:[],windshield:[],rearWindow:[]});const panel=buildPanels(m,[{id:'hood',center:[1,1.1,0],right:[0,0,-1],up:[-1,0,0],size:[1,.6]}],labels).hood;assert.ok(Math.abs(samplePanel(panel,.5,.5)[1]-1.204)<1e-4);const p={col:4,row:2,cols:8,rows:4};assert.equal(fitsPanel(panel,p),true);panel.valid[10*41+20]=0;assert.equal(fitsPanel(panel,p),false);assert.equal(samplePanel(panel,-1,.5),null);});
test('overlap: intersection blocked, touching edges and different zones accepted',()=>{assert.equal(overlap(rect,{...rect,col:3}),true);assert.equal(overlap(rect,{...rect,col:4}),false);assert.equal(overlap(rect,{...rect,row:2}),false);assert.equal(overlap(rect,{...rect,zoneId:'door-right'}),false);});
test('grid coordinates, dimensions and rotations are validated',()=>{for(const change of [{col:-1},{row:9},{cols:0},{cols:21},{cols:2.4},{rows:11},{rotation:45},{zoneId:'glass'}])assert.throws(()=>validateGrid({...rect,...change}));for(const rotation of [0,90,180,270])assert.equal(validateGrid({...rect,rotation}).rotation,rotation);});
test('stored record restores all placement fields and restricts image paths',()=>{const uid='00000000-0000-0000-0000-000000000001',r={...rect,id:uid,owner_id:uid,vehicle_id:'v1',brand:'Entreprise',logo_path:uid+'/'+uid+'.png',amount_cents:400000,revision:1,zone_id:'hood'};assert.deepEqual(mapPlacement(r,'v1').placement,rect);assert.throws(()=>mapPlacement({...r,logo_path:'https://example.test/logo.svg'},'v1'));assert.throws(()=>mapPlacement(r,'other'));});
test('concurrent collision and stale revision have distinct messages',()=>{assert.match(placementError({code:'23P01'}),/autre entreprise/);assert.match(placementError({code:'40001'}),/autre onglet/);assert.match(placementError({code:'42501'}),/non autorisée/);});
const source="const source=window.HURACAN_MODEL_BASE64?Uint8Array.from(atob(window.HURACAN_MODEL_BASE64),c=>c.charCodeAt(0)).buffer:'assets/spyder-study.glb';viewer.load(source).catch(viewerError);";
const html=`<head></head><body><script>window.HURACAN_MODEL_BASE64="AAAA";</script><script>(()=>{try{\n viewer=new CarViewer();${source}}catch(e){}})();</script></body>`;
test('extensions compile inside the original closure with STL bootstrap',()=>{const out=compileStudio(html,studio,cloud,css);assert.match(out,/lambo%2BH\.stl/);assert.match(out,/save_logo_placement/);assert.doesNotMatch(out,/HURACAN_MODEL_BASE64/);});
test('template drift fails closed',()=>assert.throws(()=>compileStudio(html.replace('viewer=new CarViewer','viewer = new CarViewer'),studio,cloud,css)));
test('public config forbids secret keys and incomplete config',()=>{assert.equal(publicConfig({}).supabaseUrl,'');assert.throws(()=>publicConfig({SUPABASE_URL:'https://project.supabase.co'}));for(const key of ['sb_secret_test','x.'+Buffer.from(JSON.stringify({role:'service_role'})).toString('base64url')+'.s'])assert.throws(()=>publicConfig({SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:key}));assert.equal(publicConfig({SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_test'}).vehicleId,'huracan-stl-v1');});
function harness(){const ctx=vm.createContext({console,URL,window:{HURACAN_CONFIG:{}},document:{baseURI:'http://localhost/'}});vm.runInContext(`const state={zoneId:'hood',center:[0,0],cols:4,rotation:0,logo:{},custom:true,occupied:[{zoneId:'hood',col:4,row:0,cols:2,rows:2}]};let dragContext=null,messages=[];function snapshot(){return {zoneId:state.zoneId,center:[...state.center],cols:state.cols,rotation:state.rotation};}function placement(){return {zoneId:state.zoneId,col:state.center[0],row:state.center[1],cols:state.cols,rows:state.rotation%180?4:2};}function isBlocked(p){return state.occupied.some(q=>q.zoneId===p.zoneId&&p.col<q.col+q.cols&&p.col+p.cols>q.col&&p.row<q.row+q.rows&&p.row+p.rows>q.row);}function update(){}function panelPoint(){}function toast(m){messages.push(m);}function $(id){return {};}class CarViewer{load(){}pick(){}destroy(){}}`+studio,ctx);vm.runInContext('update()',ctx);return ctx;}
test('slider and keyboard cannot overlap an existing logo',()=>{for(const edit of ['state.cols=6','state.center=[3,0]']){const c=harness();vm.runInContext(edit+';update()',c);assert.equal(vm.runInContext('state.cols',c),4);assert.equal(vm.runInContext('state.center[0]',c),0);}});
test('rotation rolls back when it would overlap',()=>{const c=harness();vm.runInContext("state.occupied=[{zoneId:'hood',col:0,row:2,cols:4,rows:2}];state.rotation=90;update()",c);assert.equal(vm.runInContext('state.rotation',c),0);});
test('drag preserves invalid preview for original finishDrag rollback',()=>{const c=harness();vm.runInContext('dragContext={};state.cols=6;update()',c);assert.equal(vm.runInContext('state.cols',c),6);assert.equal(vm.runInContext('isBlocked(placement())',c),true);});
test('remote inventory collision invalidates draft without silent movement',()=>{const c=harness();vm.runInContext("inventoryUpdate(()=>{state.occupied=[{zoneId:'hood',col:0,row:0,cols:4,rows:2}];update();})",c);assert.equal(vm.runInContext('lastAccepted',c),null);assert.equal(vm.runInContext('state.center[0]',c),0);});
